# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-25 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181226_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talks',
            name='topic',
            field=models.CharField(choices=[('team_culture', 'Team Culture'), ('product_management', 'Product Mgmt'), ('marketing', 'Sales & Marketing'), ('tech', 'Technology'), ('design', 'Design')], default='card', max_length=100),
        ),
    ]
