# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-25 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190224_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='last',
            field=models.BooleanField(default=False, verbose_name='last'),
        ),
    ]
