# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-09-09 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_human_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='in_line',
            field=models.IntegerField(default=0, verbose_name='Next in Line'),
        ),
    ]
